---
title: "ECDC"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

Plot barplots of variant dynamics with ECDC data

# Load data

```{r}
dlData <- FALSE
```

## |- Download variant data

```{r loadDataVariants}
# Source <https://www.ecdc.europa.eu/en/publications-data/data-virus-variants-covid-19-eueea>

# Download data
URL <- "https://opendata.ecdc.europa.eu/covid19/virusvariant/csv/data.csv"
if(dlData){
  download.file(URL, 
              destfile="data_public/tessy.csv",
              method="curl",
              extra='-L')
  # Save update
  system("git add data_public/tessy.csv; git commit -m 'update tessy data'")
}

# Load data
dat.tessy.all <- read.csv("data_public/tessy.csv", sep = ",", stringsAsFactors = FALSE)


## Clean data
# Get first day of the week
dat.tessy.all$year_week2 <- dat.tessy.all$year_week
dat.tessy.all[dat.tessy.all$year_week == "2020-53", "year_week2"] <- "2021-00"
dat.tessy.all$date1 <- as.Date(paste0(dat.tessy.all$year_week2, "-1"), "%Y-%W-%w")
# Note: I am not sure about the date format used in the data. There is an error for 2020-53, which I why I am changing it to 2021-00. This is not ideal, but this is just one week so for the moment, we are juste noting the issue, and we'll see later who to fix it. 
# - it is one week in 2020
# - there are almost not VOCs in 2020

# https://www.epochconverter.com/weeks/2021
unique(dat.tessy.all[dat.tessy.all$year_week == "2020-53", "date1"])
# Supposed to be 28-Dec
unique(dat.tessy.all[dat.tessy.all$year_week == "2021-01", "date1"])
# OK, 4-Jan
unique(dat.tessy.all[dat.tessy.all$year_week == "2020-52", "date1"])
# Supposed to be 21-Dec

dat.gisaid <- dat.tessy.all[dat.tessy.all$source == "GISAID", ]
dat.tessy <- dat.tessy.all[dat.tessy.all$source == "TESSy", ]
```

## |- Download epidemiological data, ECDC

Source <https://www.ecdc.europa.eu/en/publications-data/data-daily-new-cases-covid-19-eueea-country>

```{r}
URL <- "https://opendata.ecdc.europa.eu/covid19/nationalcasedeath_eueea_daily_ei/csv/data.csv"

dataFile <- paste0("data_public/ECDC_Cas.csv") # name file with today's date
if(dlData){
  download.file(URL, dataFile) # download file
  system("git add data_public/ECDC_Cas.csv; git commit -m 'update ecdc case data'")
}

cas.ECDC <- read.csv(dataFile, na.strings = "", fileEncoding = "UTF-8-BOM") # As suggested on the ECDC webpage

head(cas.ECDC)

# Format data
# Date
cas.ECDC$date <- as.Date(cas.ECDC$dateRep, format = "%d/%m/%Y")
#data.frame(cas.ECDC$date, cas.ECDC$dateRep) # Check

head(cas.ECDC)

# Ignore corrections
cas.ECDC[which(cas.ECDC$cases < 0), "cases"] <- NA

# Compute weekly data
cas.ECDC$year_week <- format(cas.ECDC$date, "%Y-%W")
head(cas.ECDC)
cas.ECDC.weekly <- aggregate(x = cas.ECDC$cases, by = list(country = cas.ECDC$countriesAndTerritories, year_week = cas.ECDC$year_week), FUN = sum)
head(cas.ECDC.weekly)

cas.ECDC.weekly$date1 <- as.Date(paste0(cas.ECDC.weekly$year_week, "-1"), "%Y-%W-%w")
```

## |- Clean data

### |-- Variant names

```{r}
variants.gisaid <- unique(dat.gisaid$variant)
variants.gisaid
# [1] "B.1.617.2"  "BA.1"       "BA.2"       "BA.2+L452X" "BA.3"       "BA.4"      
# [7] "BA.5"       "Other"      "UNK"  

variants.tessy <- unique(dat.tessy$variant)
variants.tessy
# [1] "B.1.1.7"         "B.1.617.2"       "Other"           "B.1.351"        
# [5] "B.1.525"         "B.1.1.7+E484K"   "P.1"             "B.1.617.1"      
# [9] "B.1.621"         "AY.4.2"          "B.1.1.529"       "SGTF"         
# [13] "C.37"            "UNK"             "B.1.616"         "B.1.617.3"      
# [17] "B.1.620"         "B.1.427/B.1.429"
```

```{r}
country <- "France"

plotVarDyn <- function(country){
  # Subset of the data for this country
  dat <- dat.gisaid[dat.gisaid$country == country & dat.gisaid$date1 >= "2021-11-01", ]

  # # Add case data (more details)
  # tmp <- cas.ECDC.weekly[cas.ECDC.weekly$country == country, ]
  # # Remove last point (incomplete)
  # tmp <- head(tmp, -1)
  # 
  # tt <- merge(dat, tmp, by = c("year_week"), all = TRUE)
  # head(tt)
  # 
  # plot(tt$date1.y, tt$x, col = 2)
  # points(tt$date1.x, tt$new_cases)
  # dat <- dat[dat$date1 >= "2021-11-01", ]
  # tail(dat)
  
  # Add estimation number cases per variant
  dat$estim.nb.variant <- dat$percent_variant / 100 * dat$new_cases
  
  # Define colors
  tmp <- MetBrewer::met.brewer("Cross", 11, direction = -1)
  # (cold for Delta, warm for Omicrons)
  cols <- c(tmp[3], tmp[6], tmp[7], tmp[8], tmp[9], tmp[10], tmp[11], gray(0.5), gray(0.2))
  names(cols) <- sort(unique(dat$variant))
  names(cols)[1] <- "Delta"
  ii <- c(1, 2, 3, 4, 6, 7) # Subset of the main lineages
  
  par(mgp = c(3, 0.5, 0), tck = - 0.02)
  
  # Function to plot axes and legend for each barplot
  plotLegAx <- function(bp){
    # Plot title
    title(country, line = 2.5)
    
    par(xpd = TRUE)
    # Legend of horizontal axis
    text(x = bp, y = 0, 
         labels = unique(dat$date1)[1:length(bp)], # Removing last one, which contains NAs
         adj = 1.1, cex = 0.6, las = 3, srt = 90)
    # Vertical axis
    axis(2, las = 1, pos = bp[1] - (bp[2] - bp[1])/2)
    
    # Legend
    legend(x = "top", col = cols[ii], legend = names(cols)[ii], horiz = TRUE, pch = 15, pt.cex = 1.5, y.intersp = 0.1, inset = c(0, -0.075), cex = 0.8, bty = "n")
    
    # Credit
    mtext(text = "Data GISAID via ECDC https://www.ecdc.europa.eu/en/publications-data/data-virus-variants-covid-19-eueea", family = "mono", cex = 0.6, line = 4, side = 1, col = gray(0.5))
    
    par(xpd = FALSE)
  }
  
  # PNG characteristics
  hpng <- 4.5 # height
  wpng <- 8 # width
  rpng <- 200 # resolution
  
  par(mar = c(4, 4, 2, 1))

  
  # Barplot 1 -- Percentages of variants
  bp1 <- barplot(percent_variant ~ variant + year_week, data = dat)
  
  f1 <- paste0("pics/ECDC_", country, "_freqs.png") # file name
  png(f1, width = wpng, height = hpng, res = rpng, units = "in")
  bp1 <- barplot(percent_variant ~ variant + year_week, data = dat, col = cols, axes = FALSE, 
                 names.arg = rep("", length(bp1)),
                 xlab = "Week (first day)", ylab = "Proportion of each variant")
  plotLegAx(bp1) 
  dev.off()
  
  # Barplot 2 -- Cases of variants
    bp2 <- barplot(estim.nb.variant ~ variant + year_week, data = dat)

  f2 <- paste0("pics/ECDC_", country, "_cases.png")
  png(f2, width = wpng, height = hpng, res = rpng, units = "in")
  bp2 <- barplot(estim.nb.variant ~ variant + year_week, data = dat, col = cols, axes = FALSE, 
                 names.arg = rep("", length(bp2)),
                 xlab = "Week (first day)", ylab = "Number of cases by variant")
  
  plotLegAx(bp2)
  dev.off()
  
}


plotVarDyn("France")
plotVarDyn("Portugal")
plotVarDyn("Germany")
plotVarDyn("Denmark")

```
  
