---
title: "Variant waves in France, TESSy"
author: "FD"
output:
  html_document: 
      code_folding: hide
      toc: TRUE
      toc_float: TRUE
      self_contained: no 
---

<!--
Header for html output
  html_document: 
      code_folding: hide
      toc: TRUE
      toc_float: TRUE
      self_contained: no 
-->

Document compiled on `r Sys.Date()`.

# Initializations

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, eval = FALSE, include = FALSE}
# This is only for evaluation in the console, not for Rmd
rm(list = ls()) 
options(warn = 2) # Turn warnings into errors to trouble-check
```

```{r}
# Package for multinom fit
library(nnet) 

# Colors
# library("MetBrewer")

# Source sliding window function
source("../covid_indicateurs/usefulFunctions.R")
# Also available here: https://github.com/flodebarre/covid_indicateurs/blob/main/usefulFunctions.R
```

```{r}
dlData <- FALSE
```

# Load and clean data

## Variant data

```{r}
# Load TESSy data
source("TESSy.R")

head(dat.gisaid.FR)
head(dat.tessy.FR)
```


```{r cleanDates}
plot(dat.tessy.FR$week)
plot(dat.gisaid.FR$week)
range(dat.tessy.FR$week)
range(dat.gisaid.FR$week)

dat.gisaid.FR$year_week2 <- dat.gisaid.FR$year_week
dat.gisaid.FR[dat.gisaid.FR$year_week2 == "2020-53", "year_week2"] <- "2021-00"

dat.tessy.FR$date1 <- as.Date(paste0(dat.tessy.FR$year_week, "-1"), "%Y-%W-%w")
dat.gisaid.FR$date1 <- as.Date(paste0(dat.gisaid.FR$year_week2, "-1"), "%Y-%W-%w")

# Check dates

plot(dat.gisaid.FR$date1)
# There is a date problem in 2020 but for the moment I decide not to care because
# - it is one week in 2020
# - there are almost not VOCs in 2020

# https://www.epochconverter.com/weeks/2021
dat.gisaid.FR[dat.gisaid.FR$year_week == "2020-53", "date1"]
# Supposed to be 28-Dec
dat.gisaid.FR[dat.gisaid.FR$year_week == "2021-01", "date1"]
# OK, 4-Jan
dat.gisaid.FR[dat.gisaid.FR$year_week == "2020-52", "date1"]
# Supposed to be 21-Dec

plot(dat.tessy.FR$date1)
```

```{r cleanVariants}
unique(dat.gisaid.FR$variant)


vars <- c("AT.1", 
          "AY.4.2", 
          "B.1.1.529", 
          "B.1.1.7", 
          "B.1.1.7+E484K", 
          "B.1.351", 
          "B.1.427/B.1.429", 
          "B.1.525", 
          "B.1.526",
          "B.1.616", 
          "B.1.617", 
          "B.1.617.1", 
          "B.1.617.2", 
          "B.1.617.3", 
          "B.1.620", 
          "B.1.621", 
          "B.1.640", 
          "C.1.2", 
          "C.37", 
          "P.1", 
          "P.3", 
          "UNK", 
          "Other")

OMS <- c("Other", 
          "Delta", 
          "Omicron", 
          "Alpha", 
          "Alpha", 
          "Beta", 
          "Epsilon", 
          "Eta", 
          "Iota",
          "Other", 
          "Other", # B.1.617
          "Kappa", 
          "Delta", 
          "Other", 
          "Other", 
          "Mu", 
          "B.1.640", 
          "C.1.2", 
          "Lambda", 
          "Gamma", 
          "Theta", 
          "Unknown", 
          "Other")

dic.OMS <- OMS
names(dic.OMS) <- vars
dic.OMS


dat.gisaid.FR$varOMS <- dic.OMS[dat.gisaid.FR$variant]
unique(dat.gisaid.FR$varOMS)

head(dat.gisaid.FR)

unique(OMS)

dic.VOCs <- c("Other", 
          "Delta", 
          "Omicron", 
          "Alpha", 
          "Alpha", 
          "Beta", 
          "Other", 
          "Other", 
          "Other",
          "Other", 
          "Other", # B.1.617
          "Other", 
          "Delta", 
          "Other", 
          "Other", 
          "Other", 
          "Other", 
          "Other", 
          "Other", 
          "Gamma", 
          "Other", 
          "Unknown", 
          "Other")
names(dic.VOCs) <- vars
dic.VOCs

dat.gisaid.FR$VOC <- dic.VOCs[dat.gisaid.FR$variant]  
unique(dat.gisaid.FR$VOC)
```


## Epidemiological data

Source: <https://www.data.gouv.fr/fr/datasets/donnees-relatives-aux-resultats-des-tests-virologiques-covid-19/#>, `sp-pos-quot-fra-xxx.csv`

```{r}
URL <- "https://www.data.gouv.fr/fr/datasets/r/dd0de5d9-b5a5-4503-930a-7b08dc0adc7c"

dataFile <- paste0("data/FranceCas.csv") # name file with today's date
if(dlData){
  download.file(URL, dataFile) # download file
}

dat.France <- read.csv(dataFile, sep = ";", stringsAsFactors = FALSE)
head(dat.France)

dat.France$date <- as.Date(dat.France$jour)

# Remove age classes
dat.France <- dat.France[which(dat.France$cl_age90 == 0), ]


dat.France$P7j <- sliding.window(dat.France$P)

inona <- 4:(nrow(dat.France)-3)

# Smooth data
# spar parameter controls the level of smoothing
tmp <- smooth.spline(as.numeric(as.Date(dat.France[inona, ]$jour) - as.Date(min(dat.France$jour))), dat.France[inona,]$P7j, 
                     spar = 0.2)

# Check
plot(tmp)

dat.France$Psmoothed <- c(rep(NA, 3), tmp$y, rep(NA, 3))

```

## Epidemiological data, ECDC

source <https://www.ecdc.europa.eu/en/publications-data/data-daily-new-cases-covid-19-eueea-country>

```{r}
URL <- "https://opendata.ecdc.europa.eu/covid19/nationalcasedeath_eueea_daily_ei/csv/data.csv"

dataFile <- paste0("data_public/ECDC_Cas.csv") # name file with today's date
if(dlData){
  download.file(URL, dataFile) # download file
  system("git add data_public/ECDC_Cas.csv; git commit -m 'update ecdc case data'")
}

cas.ECDC <- read.csv(dataFile, na.strings = "", fileEncoding = "UTF-8-BOM") # As suggested on the ECDC webpage

head(cas.ECDC)

# Format data
# Date
cas.ECDC$date <- as.Date(cas.ECDC$dateRep, format = "%d/%m/%Y")
#data.frame(cas.ECDC$date, cas.ECDC$dateRep) # Check


head(cas.ECDC)

# Ignore corrections
cas.ECDC[which(cas.ECDC$cases < 0), "cases"] <- NA

cas.ECDC.FR <- cas.ECDC[which(cas.ECDC$countriesAndTerritories == "France"), ]

par(lwd = 1)
plot(cas.ECDC.FR$date, cas.ECDC.FR$cases)

# Sort by date
cas.ECDC.FR <- cas.ECDC.FR[order(cas.ECDC.FR$date), ]

# Make sure dates are consecutive
stopifnot(all(diff(cas.ECDC.FR$date) == 1))
cas.ECDC.FR$cases7J <- sliding.window(cas.ECDC.FR$cases)

plot(cas.ECDC.FR$date, cas.ECDC.FR$cases7J)

# Smoothen the data
inona <- 4:(nrow(cas.ECDC.FR)-3)

# spar parameter controls the level of smoothing
tmp <- smooth.spline(as.numeric(as.Date(cas.ECDC.FR[inona, ]$date) - as.Date(min(cas.ECDC.FR$date))), cas.ECDC.FR[inona,]$cases7J, 
                     spar = 0.2)

cas.ECDC.FR$Psmoothed <- c(rep(NA, 3), tmp$y, rep(NA, 3))

lines(cas.ECDC.FR$date, cas.ECDC.FR$Psmoothed, col = 2)
```

# Analyse

```{r}
# Aggregate data by VOC for each date
aggVOC <- aggregate(dat.gisaid.FR$number_detections_variant, by = list(date1 = dat.gisaid.FR$date1, VOC = dat.gisaid.FR$VOC), FUN = sum)

# Sample sizes
aggSam <- aggregate(aggVOC$x, by = list(date1 = aggVOC$date1), FUN = sum)
names(aggSam)[2] <- "tot"

aggVOC <- merge(aggVOC, aggSam, by = "date1")

aggVOC$prop <- aggVOC$x / aggVOC$tot

# Add case data (ECDC)
tmp <- merge(aggVOC, cas.ECDC.FR, by.x = "date1", by.y = "date")
tmp$cases.sum7J <- 7 * tmp$cases7J
aggVOC <- tmp

#--------------------------
# Version without Unknown
aggVOC2 <- aggVOC[which(aggVOC$VOC != "Unknown"), c("date1", "VOC", "x")]
tmp <- aggregate(aggVOC2$x, by = list(date1 = aggVOC2$date1), FUN = sum)
names(tmp)[2] <- "tot"
aggVOC2 <- merge(aggVOC2, tmp, by = "date1")
aggVOC2$p <- aggVOC2$x / aggVOC2$tot

# Add case data (ECDC)
tmp <- merge(aggVOC2, cas.ECDC.FR, by.x = "date1", by.y = "date")
tmp$cases.sum7J <- 7 * tmp$cases7J
aggVOC2 <- tmp


# Check data format
# Make sure that all variants are listed at all dates
checkFormat <- aggregate(aggVOC$x, by = list(VOC = aggVOC$VOC), FUN = length)
stopifnot(all(checkFormat$x == checkFormat$x[1]))

#"Other"   "Delta"   "Omicron" "Alpha"   "Beta"    "Gamma"   "UNK"  

# Create matrix for multinom fit
mat <- data.frame("Alpha" = aggVOC[aggVOC$VOC == "Alpha", "x"])
mat

VOCs <- sort(unique(aggVOC$VOC))
VOCs[3] <- "Gamma"
VOCs[4] <- "Delta"
# Because alphabetical order different

for(voc in VOCs[-1]){
  mat[, voc] <- aggVOC[aggVOC$VOC == voc, "x"]
}
mat <- as.matrix(mat)

time <- aggVOC[aggVOC$VOC == "Alpha", "date1"]

timeSinceFirstDay <- as.numeric(time - min(time))


## Null model
m0 <- multinom(mat ~ 1)
summary(m0)

# Add weights to make sure that initial values remain as in the data
# (otherwise fit says large proportion still in Nov, problem)
# Note: would need to go check in GISAID directly to add the missing weeks
weights <- c(rep(10000, 3), rep(1, nrow(mat) - 3))
m1 <- multinom(mat ~ timeSinceFirstDay, 
               weights = weights)
summary(m1)

minDate <- min(dat.France$date)
dates <- seq(minDate, max(aggVOC$date1), by = "day")
dates2 <- seq(as.numeric(minDate - min(time)), max(timeSinceFirstDay), by = 1)

dates <- as.data.frame(dates)
names(dates) <- "date1"
pred <- data.frame(timeSinceFirstDate = dates2, date = dates, predict(m1, newdata = data.frame(timeSinceFirstDay = dates2), type = "prob"))

# Check output
head(pred)
all(apply(pred[, 3:ncol(pred)], 1, sum) > 0.999)

pred0 <- pred


## This was necessary before the weights, 
## now not necessary, but kept for legacy
# ## Set all VOCs to 0 before key date
# zeroDate <- as.Date("2020-12-15")
# ii <- which(pred$date1 < zeroDate)
# theVOCs <- c("Alpha", "Beta", "Gamma", "Delta", "Omicron")
# 
# z <- apply(pred[ii, theVOCs], 1, sum)
# z
# fac <- 0.1
# pred[ii, theVOCs] <- fac*pred[ii, theVOCs]
# pred[ii, "Other"] <- pred[ii, "Other"] + (1-fac)*z

# Merge with case data
predCase <- merge(pred, dat.France, by.x = "date1", by.y = "date")

head(predCase)

# pred <- pred0
```

# Plot

```{r defineColors}
# pal <- met.brewer("Redon", 10, "discrete")
# rbind(1:10, pal[1:10])

# colAlpha <- pal[2]
# colBeta <- pal[10]
# colGamma <- pal[9]
# colDelta <- pal[1]
# colOmicron <- pal[6]
colOther <- gray(0.4)
colUnknown <- gray(0.8)

colAlpha <- "#1f1dff"
colBeta <- "#6322b9"
colGamma <- "#4760e9"
colDelta <- "#66babf"
colOmicron <- "#f55c30"


```

## Proportions, raw


```{r proportionsRaw}
# Rename VOCs to reorder columns
dicc <- c("1_Omicron", "2_Delta", "3_Gamma", "4_Beta", "5_Alpha", "6_Unknown", "7_Other")
names(dicc) <- c("Omicron", "Delta", "Gamma", "Beta", "Alpha", "Unknown", "Other")

dicc2 <- c("7_Omicron", "6_Delta", "5_Gamma", "4_Beta", "3_Alpha", "2_Unknown", "1_Other")
names(dicc2) <- names(dicc)

aggVOC$VOC2 <- dicc[aggVOC$VOC]
aggVOC2$VOC2 <- dicc[aggVOC2$VOC]

aggVOC$VOC3 <- dicc2[aggVOC$VOC]
aggVOC2$VOC3 <- dicc2[aggVOC2$VOC]

?barplot
barplot(aggVOC$prop ~ aggVOC$VOC2 + aggVOC$date1, col = 1:7)

cc <- vapply(names(dicc), function(i) get(paste0("col", i)), FUN.VALUE = "x")
ii <- which(names(cc)!= "Unknown")

opar <- par(lwd = 0.01)

barplot(aggVOC2$prop ~ aggVOC2$VOC2 + aggVOC2$date1, col = cc[ii], border = "gray")

aggVOC$VOC
```


## Proportions, multinom fit

```{r plotProps, fig.width=8, fig.height=4.5}

# Save pred
opred <- pred

names(pred)

pred <- pred[, c("timeSinceFirstDate", "date1", "Omicron", "Delta", "Gamma", "Beta", "Alpha", "Other", "Unknown")]

# Initialize plot
par(las = 1)
par(mar = c(4, 2, 2, 5), mgp = c(2.5, 0.5, 0), tck = - 0.02)

xx <- as.Date(pred$date1)
plot(xx, 
     rep(0, nrow(pred)),
     type = "n", 
     ylim = c(0, 1), 
     xlab = "", 
     ylab = "", 
     frame.plot = FALSE, axes = FALSE)

# Axes
xl <- seq(minDate, Sys.Date(), by = "month")
axis(1, at = xl, labels = format(xl, "%b"), 
     lwd = 0, lwd.ticks = 1, pos = 0)
axis(1, at = as.Date(c("2020-07-01", "2021-07-01", "2022-02-01")), labels = seq(2020, 2022), line = 0, lwd = 0)

axis(2, pos = minDate, lwd = 0, lwd.ticks = 1)


# Plot each variant
jvals <- 3:9
for(j in jvals){
  if(j == 3){
    y1 <- rep(0, nrow(pred))
    y2 <- pred[, 3]
  }else{
    y2 <- apply(pred[, 3:j], 1, sum) 
  }
  if(j == 4){
    y1 <- pred[, 3]
  }
  if(j > 4){
    y1 <- apply(pred[, 3:(j-1)], 1, sum)
  }
  
  
  print(paste0("col", names(pred)[j]))
  print(get(paste0("col", names(pred)[j])))
  polygon(c(xx, rev(xx), xx[1]), c(y1, rev(y2), y1[1]), 
          col = get(paste0("col", names(pred)[j])), 
          border = NULL)
}

# Legend
par(xpd = TRUE)
legend("right", inset=c(-0.15,0), 
       legend = rev(paste0(names(pred)[jvals])), 
       pch = 15, 
       col = rev(vapply(jvals, function(j) get(paste0("col", names(pred)[j])), FUN.VALUE = "x")), pt.cex = 2, bty = "n")

title(main = "SARS-CoV-2 variants in France")

# Credits
mtext(paste0("@flodebarre, after @firefoxx66, ", Sys.Date(), "
Data: GISAID via ECDC, https://opendata.ecdc.europa.eu/covid19/virusvariant/csv/data.csv
Code: https://github.com/flodebarre/gisaidCovid_public/blob/main/variantWavesFrance.Rmd"), family = "mono", cex = 0.5, side = 1, line = 2.5, col = gray(0.3), adj = 0)

pred <- opred
```


## Abundances, raw

```{r abundancesRaw}
aggVOC$n <- aggVOC$prop * aggVOC$cases.sum7J

barplot(aggVOC$n ~ aggVOC$VOC2 + aggVOC$date1, col = 1:7)

opar <- par(lwd = 0.01)

cc2 <- vapply(sort(dicc2), function(i) get(paste0("col", substr(i, 3, nchar(i)))), FUN.VALUE = "x")
ii2 <- which(names(cc2)!= "Unknown")

aggVOC2$date <- as.Date(aggVOC2$date1)

aggVOC2$n <- aggVOC2$p * aggVOC2$cases.sum7J

barplot(aggVOC2$n ~ aggVOC2$VOC3 + aggVOC2$date, col = cc2[ii2], border = "gray")

aggVOC$VOC
```

## Abundances

```{r plotAbundances, fig.width=16, fig.height=9}

# Initialize plot
par(las = 1)
par(mar = c(4, 2.5, 2, 5), mgp = c(2.5, 0.5, 0), tck = - 0.01)

xx <- as.Date(predCase$date1)
plot(xx, 
     rep(0, nrow(predCase)),
     type = "n", 
     ylim = c(0, max(predCase$Psmoothed, na.rm = TRUE)), 
     xlab = "", 
     ylab = "", 
     frame.plot = FALSE, axes = FALSE)

# Axes
xl <- seq(minDate, Sys.Date(), by = "month")
axis(1, at = xl, labels = format(xl, "%b"), 
     lwd = 0, lwd.ticks = 1, pos = 0)
axis(1, at = as.Date(c("2020-07-01", "2021-07-01", "2022-02-01")), labels = seq(2020, 2022), line = 0, lwd = 0)

axis(2, pos = minDate, lwd = 0, lwd.ticks = 1)


# Plot each variant
jvals <- 3:9
for(j in jvals){
  if(j == 3){
    y1 <- rep(0, nrow(predCase))
    y2 <- predCase[, 3]
  }else{
    y2 <- apply(predCase[, 3:j], 1, sum) 
  }
  if(j == 4){
    y1 <- predCase[, 3]
  }
  if(j > 4){
    y1 <- apply(predCase[, 3:(j-1)], 1, sum)
  }
  
  
  print(paste0("col", names(predCase)[j]))
  print(get(paste0("col", names(predCase)[j])))
  
  polygon(c(xx, rev(xx), xx[1]), c(y1 * predCase$Psmoothed, rev(y2 * predCase$Psmoothed), y1[1] * predCase$Psmoothed[1]), 
          col = get(paste0("col", names(predCase)[j])), 
          border = NULL)
  
   #readline(prompt="Press [enter] to continue")
}

# Legend
par(xpd = TRUE)
legend("right", inset=c(-0.05,0), 
       legend = rev(paste0(names(predCase)[jvals])), 
       pch = 15, 
       col = rev(vapply(jvals, function(j) get(paste0("col", names(predCase)[j])), FUN.VALUE = "x")), pt.cex = 2, bty = "n",)

title(main = "SARS-CoV-2 variants in France")

# Credits
mtext(paste0("@flodebarre, after @TWenseleers, ", Sys.Date(), "
Data: GISAID via ECDC, https://opendata.ecdc.europa.eu/covid19/virusvariant/csv/data.csv
Code: https://github.com/flodebarre/gisaidCovid_public/blob/main/variantWavesFrance.Rmd"), family = "mono", cex = 0.5, side = 1, line = 2.5, col = gray(0.3), adj = 0)
```

 